from tests.fakes.fake_repositories.fake_booking_repository import FakeBookingRepository
from tests.fakes.fake_repositories.fake_document_repository import FakeDocumentRepository
from tests.fakes.fake_repositories.fake_flight_repository import FakeFlightRepository
from tests.fakes.fake_repositories.fake_passenger_repository import FakePassengerRepository
from tests.fakes.fake_repositories.fake_ticket_repository import FakeTicketRepository