from src.entidades.AsignacionVuelo import AsignacionVueloBase, AsignacionVueloDesdeDB
from src.entidades.Avion import AvionBase, AvionDesdeDB
from src.entidades.CertificacionStaff import CertificacionStaffBase, CertificacionStaffDesdeDB
from src.entidades.Documento import DocumentoBase, DocumentoDesdeDB
from src.entidades.Pasajero import PasajeroBase, PasajeroDesdeDB
from src.entidades.Ruta import RutaBase, RutaDesdeDB
from src.entidades.TarjetaEmbarque import TarjetaEmbarqueBase, TarjetaEmbarqueDesdeDB
from src.entidades.Venta import VentaBase, VentaDesdeDB
from src.entidades.Vuelo import VueloBase, VueloDesdeDB
from src.entidades.Staff import StaffBase, StaffDesdeDB