from src.managers.AsignacionesVuelosManager import AsignacionesVuelosManager
from src.managers.CertificacionesStaffManager import CertificacionesStaffManager
from src.managers.DBManager import DBManager
from src.querys import *
from src.managers.TablaManager import TablaManager
from src.managers.TarjetasEmbarqueManager import TarjetasEmbarqueManager
from src.managers.TriggerManager import TriggerManager
from src.managers.VentasManager import VentasManager
from src.managers.VuelosManager import VuelosManager
from src.managers.DocumentosManager import DocumentosManager