from src.AsignacionesVuelosManager import AsignacionesVuelosManager
from src.CertificacionesStaffManager import CertificacionesStaffManager
from src.DBManager import DBManager
from src.GeneradorDatos import GeneradorDatos
from src.querys import *
from src.TablaManager import TablaManager
from src.TarjetasEmbarqueManager import TarjetasEmbarqueManager
from src.TriggerManager import TriggerManager
from src.VentasManager import VentasManager
from src.VuelosManager import VuelosManager
from src.DocumentosManager import DocumentosManager