USE airline;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE sale_stasuses;
TRUNCATE TABLE documents;
TRUNCATE TABLE document_types;
TRUNCATE TABLE boarding_passes;
TRUNCATE TABLE sales;
TRUNCATE TABLE passengers;
TRUNCATE TABLE roles;
TRUNCATE TABLE boarding_pass_statuses;
TRUNCATE TABLE flights;
TRUNCATE TABLE crew_assignments;
TRUNCATE TABLE routes;
TRUNCATE TABLE airplanes;
TRUNCATE TABLE flight_statuses;
TRUNCATE TABLE staff;
TRUNCATE TABLE staff_certifications;
TRUNCATE TABLE ariplane_statuses;
TRUNCATE TABLE estados_staff;
TRUNCATE TABLE positions;
TRUNCATE TABLE audit_logs;
SET FOREIGN_KEY_CHECKS = 1;